// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataResultInterface is an autogenerated mock type for the DataResultInterface type
type DataResultInterface struct {
	mock.Mock
}

// Json provides a mock function with given fields:
func (_m *DataResultInterface) Json() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
