// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetaResultInterface is an autogenerated mock type for the MetaResultInterface type
type MetaResultInterface struct {
	mock.Mock
}

// buildPageTotal provides a mock function with given fields:
func (_m *MetaResultInterface) buildPageTotal() {
	_m.Called()
}
